name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: run
      run:  echo chmod +x blah.sh  echo /runner/blahblah/run_deploy  let a=1  let b=0  let c=a/b -bash:let:c=a/b:division by 0 !error token is "b"  echo ?1
    - name: configure
      run: ! Scala=status deployment uri=https://github.com/zachwylde00/lifewriter.application.A.I./actions/workflows/scala.yml/badge.svg?event=deployment
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: Run
      run: deployment-Scala_CI-test
