name: Jekyll site CI

on: [push]

jobs:
  status:[![Jekyll site CI](https://github.com/zachwylde00/lifewriter.application.ci_ai_automated_repo-SUB-Z-dfa-/actions/workflows/jekyll.yml/badge.svg)](https://github.com/zachwylde00/lifewriter.application.ci_ai_automated_repo-SUB-Z-dfa-/actions/workflows/jekyll.yml)
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
